import type { NormalizedSocialInput } from "@/lib/apify/unified-provider";

export interface YouTubeScrapeOptions {
  maxResults: number;
  maxResultsShorts: number;
  maxResultStreams: number;
  downloadSubtitles: boolean;
  subtitlesLanguage: string;
  oldestPostDate?: string;
  sortVideosBy: "NEWEST" | "MOST_POPULAR" | "OLDEST";
}

export const defaultYouTubeOptions: YouTubeScrapeOptions = {
  maxResults: 50,
  maxResultsShorts: 10,
  maxResultStreams: 5,
  downloadSubtitles: false,
  subtitlesLanguage: "en",
  sortVideosBy: "NEWEST",
};

/**
 * Build YouTube Actor input from normalized user input.
 * YouTube Actor h7sDV53CddomktSi5 supports channel URLs, video URLs, handles.
 */
export function buildYouTubeInput(
  normalized: NormalizedSocialInput,
  options: Partial<YouTubeScrapeOptions> = {},
): Record<string, unknown> {
  const opts = { ...defaultYouTubeOptions, ...options };
  const startUrl = normalized.normalizedUrl;

  if (!startUrl) {
    throw new Error("YouTube URL is required.");
  }

  return {
    searchQueries: [],
    maxResults: opts.maxResults,
    maxResultsShorts: opts.maxResultsShorts,
    maxResultStreams: opts.maxResultStreams,
    startUrls: [{ url: startUrl }],
    downloadSubtitles: opts.downloadSubtitles,
    subtitlesLanguage: opts.subtitlesLanguage,
    subtitlesFormat: "srt",
    sortingOrder: "relevance",
    dateFilter: "all",
    videoType: "video",
    lengthFilter: "any",
    oldestPostDate: opts.oldestPostDate,
    sortVideosBy: opts.sortVideosBy,
    aiVideoDescription: false,
    aiVideoSummary: false,
    saveSubsToKVS: false,
    preferAutoGeneratedSubtitles: false,
  };
}
